### ISSUE TITLE
Any way to mark generated code with [Serializable]?

### ISSUE THREAD

**Issue by mfandre** [antlr/antlr4-csharp#12]
I create a grammar and in the code generated listeners I want to mark then with [Serializable], its possible?

**Comment by sharwell** [comment]
Can you provide some additional information about your use case? The reason I ask is the listeners themselves do not contain any data, so there is no need to serialize them as-is. In addition, the parse tree itself is not serializable so serializing the listeners does not remove the need to parse your input again.

Making the types serializable dramatically increases the development cost associated with preserving backwards compatibility and limits the ability to make many types of improvements that may help users not needing to serialize data. It's something we want to avoid if there is any other way to address your concerns.

**Comment by mfandre** [comment]
Hi Sam,

Thx for reply,

My problem is that I need save my object at a disk and my Listener is a
part of my object. Imagine I have a program that it saves a state, when
reloading it need to back to the last known state. To do this I`m saving my
object at the disk (serializing), and on reload I`m deserializing. But as
my listener is part of the object, C # complains that he is not marked as
[Serializable].


On Tue, May 26, 2015 at 6:10 PM, Sam Harwell <notifications@github.com>
wrote:

> Can you provide some additional information about your use case? The
> reason I ask is the listeners themselves do not contain any data, so there
> is no need to serialize them as-is. In addition, the parse tree itself is
> not serializable so serializing the listeners does not remove the need to
> parse your input again.
>
> Making the types serializable dramatically increases the development cost
> associated with preserving backwards compatibility and limits the ability
> to make many types of improvements that may help users not needing to
> serialize data. It's something we want to avoid if there is any other way
> to address your concerns.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/antlr/antlr4-csharp/issues/12#issuecomment-105665752>.
>



-- 
att.
André de Mattos Ferraz

**Comment by sharwell** [comment]
I would suggest taking the following approach instead.

1. Mark the listener field with `[NonSerialized]`.
2. If your listener needs to be non-null after deserialization, add a method to your class which is marked with `[OnDeserialized]`. In the method, assign a new instance to your listener field.

    ```csharp
    [NonSerialized]
    private MyListener _listener;

    [OnDeserialized]
    internal void HandleOnDeserialized(StreamingContext context)
    {
        _listener = new MyListener();
    }
    ```

**Comment by mfandre** [comment]
I will test this approach tomorrow. But I think it will work!!! Thx for reply.

**Comment by mfandre** [comment]
Sam,

Thx, worked perfectly!

On Tue, May 26, 2015 at 11:20 PM, Sam Harwell <notifications@github.com>
wrote:

> I would suggest taking the following approach instead.
>
>    1. Mark the listener field with [NonSerialized].
>    2.
>
>    If your listener needs to be non-null after deserialization, add a
>    method to your class which is marked with [OnDeserialized]. In the
>    method, assign a new instance to your listener field.
>
>    [NonSerialized]private MyListener _listener;
>
>    [OnDeserialized]internal void HandleOnDeserialized(StreamingContext context)
>    {
>        _listener = new MyListener();
>    }
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/antlr/antlr4-csharp/issues/12#issuecomment-105725215>.
>



-- 
att.
André de Mattos Ferraz

**Comment by whitten** [comment]
Is this important enough to justify a pull request ?

**Comment by sharwell** [comment]
@whitten The changes were made in @mfandre's own code. No changes were needed in ANTLR to fully support his usage scenario.

**Comment by whitten** [comment]
I thought the changes were in the generated code.
i.e. that the he added [NonSerialized] to the interface code that ANTLR had originally created.

David
