### ISSUE TITLE
File rename not reflected in "Antlr4.vs2013.sln"

### ISSUE THREAD

**Issue by jmclain** [antlr/antlr4-csharp#14]
"runtime\CSharp\Antlr4.Runtime\Sharpen\Compat\HashSet`1.cs" was renamed to "runtime\...\HashSet.cs", but the solution "Antlr4.vs2013.sln" was not updated to reflect this. Does not compile in Visual Studio.

**Comment by ericvergnaud** [comment]
Hi,
thanks we’re aware of that, we’re in the middle of some refactoring, will get on this asap.
Eric
