### ISSUE TITLE
Global alias conflicts with .NET 4.0

### ISSUE THREAD

**Issue by nippur72** [antlr/antlr4-csharp#8]
Reopening [this issue](https://github.com/antlr/antlr4/issues/837):

Using the C# runtime (`Antlr4.Runtime.dll`) in a .NET 4.0 Visual Studio 2013 project, causes alias  conflict for the following types: `ConcurrentDictionary`, `HashSet`, `Tuple`, `Enumerable`, `ExtensionAttribute`.

Of the conflicting files, `ConcurrentDictionary`, `HashSet` and `Tuple` are from the `Sharpen` namespace, while `Enumerable` is from namespace `System.Linq` and `ExtensionAttribute` is from namespace `System.Runtime.CompilerServices`.

The problem occurs only with .NET 4.0.

Actually I fixed by forking `antlr4-csharp`, deleting the conflicting files from the \Sharpen\Compat\ directory, changing the target to .NET 4.0 and building my own custom .dll.

**Comment by stevebuckco** [comment]
We're having the same issue and do not want to create a custom version.  Is there any chance this will get addressed?

**Comment by ericvergnaud** [comment]
Yes, if you send out a small project which exhibits the issue.

**Comment by ViceIce** [comment]
Hi,

i wrote a litle script to build the assembly for different framework versions.

See ViceIce/antl4-csharp@a114804b9f8919de29ef2508308fd7e249dae44c

**Comment by superraz375** [comment]
Had this issue as well.

I alsosolved it by deleting the Sharpen/Compat folder and then compiling the DLL from source.

**Comment by parrt** [comment]
We've pulled in the commit to fix.

https://github.com/ViceIce/antlr4-csharp/commit/704cd0863bac43ebb8f4c01bb39c6d3d26b32128

**Comment by parrt** [comment]
@ViceIce I don't see your script. (link is bad)

**Comment by parrt** [comment]
@superraz375 Are you saying we just need to do a clean build to fix?

**Comment by ViceIce** [comment]
Sorry!  Wrong link.

See ViceIce/antlr4-csharp@a114804b9f8919de29ef2508308fd7e249dae44c

**Comment by parrt** [comment]
Ah.  so just that little tweak is enough to resolve this issue? If so, I will add it.

**Comment by ViceIce** [comment]
Yes, one only needs some compile time constants.

We use it at sharepoint 2010 and 2013 solutions, so we build it for net35 and net45 (net35 runtime compatible, no `NET45PLUS` constant)

**Comment by ViceIce** [comment]
See https://github.com/ViceIce/antlr4-csharp/releases/latest for sample nuget package.

**Comment by sharwell** [comment]
@ViceIce I'm curious if the approach in [this NuGet package](https://www.nuget.org/packages/Antlr4.Runtime/4.4.1-alpha001) works for you. The [Assembly Strong Name Policy](https://github.com/tunnelvisionlabs/antlr4cs#assembly-strong-name-policy) describes the way it should work (seamlessly) across the 8 different supported runtimes.

**Comment by ViceIce** [comment]
@sharewell We haven't tested that version.

**Comment by ViceIce** [comment]
@sharwell We can not use that version, because the net45 assembly uses `System.Collections.Generic.IReadOnlyList<T>`, which is not available at net35. So the api is not compatible.

**Comment by sharwell** [comment]
@ViceIce It sounds like you installed the 4.3.0 version of the package. I changed the signature in 4.4.1 to correct that incompatibility.

**Comment by ViceIce** [comment]
@sharwell I checked [Antlr4.Runtime.4.4.1-alpha001](https://www.nuget.org/packages/Antlr4.Runtime/4.4.1-alpha001) some minutes ago. The assembly at net45 folder  uses `System.Collections.Generic.IReadOnlyList<T>` at `Antlr4.Runtime.ParserRuleContext.GetRuleContexts`

**Comment by sharwell** [comment]
@ViceIce Thanks for the feedback. Looks like it was changed in tunnelvisionlabs/antlr4cs#92 which was merged after 4.4.1 was released. I'll get a new build out tonight or tomorrow so more eyes can be on this.

**Comment by ViceIce** [comment]
@sharwell I'll look at it and maybe we can switch back to official build.

**Comment by sharwell** [comment]
@ViceIce Here you go:
https://www.nuget.org/packages/Antlr4/4.5.0-alpha002

**Comment by ViceIce** [comment]
@sharwell Is it compatible with the default C#-Target of Antlr 4.5 or do we have to rebuild parser and lexer with another target?

**Comment by sharwell** [comment]
@ViceIce I'm not sure what you mean. There are never any manual steps with my target. Everything is automatically generated and tracked during the build process. The NuGet package includes the correct version of the ANTLR tool and templates needed for this process, as well as the runtime library which you reference.

**Comment by ViceIce** [comment]
@sharwell We recently switched from your [Antlr 4.3 release](https://www.nuget.org/packages/Antlr4.Runtime/4.3.0) to the official [Antlr 4.5 release](http://www.antlr.org/download.html), so we have to regenerate if we switch back. I will give it a try (next week).

**Comment by sharwell** [comment]
@ViceIce Switching should be as simple as reverting the change you made. I've preserved *almost* perfect forward API compatibility from 4.3 through 4.5 specifically so you users wouldn't have to put effort into the upgrade process.

**Comment by ViceIce** [comment]
@sharwell See [#107](https://github.com/tunnelvisionlabs/antlr4cs/issues/107)
